NASDAQ = {
"NVDA": {"name": "Nvidia", "sector": "Semiconductors"},
"AAPL": {"name": "Apple", "sector": "Technology"},  # Consumer Electronics
"MSFT": {"name": "Microsoft", "sector": "Technology"},  # Software & Services
"AMZN": {"name": "Amazon", "sector": "Consumer Discretionary"},  # Internet & Direct Retail
"GOOG": {"name": "Alphabet Class C", "sector": "Communication Services"},  # Media & Internet
"GOOGL": {"name": "Alphabet Class A", "sector": "Communication Services"},
"META": {"name": "Meta Platforms", "sector": "Communication Services"},
"TSLA": {"name": "Tesla", "sector": "Consumer Discretionary"},  # Auto Manufacturers
"AVGO": {"name": "Broadcom", "sector": "Semiconductors"},
"NFLX": {"name": "Netflix", "sector": "Communication Services"},
"COST": {"name": "Costco", "sector": "Consumer Staples"},
"ASML": {"name": "ASML Holding", "sector": "Semiconductors"},
"TMUS": {"name": "T-Mobile US", "sector": "Communication Services"},
"CSCO": {"name": "Cisco Systems", "sector": "Technology"},  # Networking Hardware
"ISRG": {"name": "Intuitive Surgical", "sector": "Health Care"},
"AZN": {"name": "AstraZeneca", "sector": "Health Care"},
"LIN": {"name": "Linde", "sector": "Materials"},
"PEP": {"name": "PepsiCo", "sector": "Consumer Staples"},
"AMD": {"name": "Advanced Micro Devices", "sector": "Semiconductors"},
"QCOM": {"name": "Qualcomm", "sector": "Semiconductors"},
"ADBE": {"name": "Adobe", "sector": "Technology"},  # Software
"TXN": {"name": "Texas Instruments", "sector": "Semiconductors"},
"INTU": {"name": "Intuit", "sector": "Technology"},  # Software Services
"VZ": {"name": "Verizon", "sector": "Communication Services"},
"BKNG": {"name": "Booking Holdings", "sector": "Consumer Discretionary"},  # Online Travel
"AMAT": {"name": "Applied Materials", "sector": "Semiconductors"},
"AMGN": {"name": "Amgen", "sector": "Health Care"},
"HON": {"name": "Honeywell", "sector": "Industrials"},
"PDD": {"name": "Pinduoduo", "sector": "Consumer Discretionary"},  # Internet Retail
"CMCSA": {"name": "Comcast", "sector": "Communication Services"},
"LRCX": {"name": "Lam Research", "sector": "Semiconductors"},
"LULU": {"name": "Lululemon Athletica", "sector": "Consumer Discretionary"},
"MAR": {"name": "Marriott International", "sector": "Consumer Discretionary"},
"MRVL": {"name": "Marvell Technology", "sector": "Semiconductors"},
"MELI": {"name": "Mercado Libre", "sector": "Consumer Discretionary"},  # Internet Retail
"MCHP": {"name": "Microchip Technology", "sector": "Semiconductors"},
"MU": {"name": "Micron Technology", "sector": "Semiconductors"},
"MSTR": {"name": "MicroStrategy", "sector": "Technology"},  # Software Services
"MDLZ": {"name": "Mondelez International", "sector": "Consumer Staples"},
"MNST": {"name": "Monster Beverage", "sector": "Consumer Staples"},
"NXPI": {"name": "NXP Semiconductors", "sector": "Semiconductors"},
"ORLY": {"name": "O’Reilly Automotive", "sector": "Consumer Discretionary"},
"ODFL": {"name": "Old Dominion Freight Line", "sector": "Industrials"},
"ON": {"name": "Onsemi", "sector": "Semiconductors"},
"PCAR": {"name": "Paccar", "sector": "Industrials"},
"PLTR": {"name": "Palantir Technologies", "sector": "Technology"},  # Software
"PANW": {"name": "Palo Alto Networks", "sector": "Technology"},  # Security Software
"PAYX": {"name": "Paychex", "sector": "Financials"},  # Business Services
"PYPL": {"name": "PayPal Holdings", "sector": "Financials"},  # FinTech
"REGN": {"name": "Regeneron Pharmaceuticals", "sector": "Health Care"}
}

NIFTY50 = {
"ADANIPORTS": "Adani Ports and Special Economic Zone Ltd",
"ASIANPAINT": "Asian Paints Ltd",
"AXISBANK": "Axis Bank Ltd",
"BAJAJ-AUTO": "Bajaj Auto Ltd",
"BAJFINANCE": "Bajaj Finance Ltd",
"BAJAJFINSV": "Bajaj Finserv Ltd",
"BHARTIARTL": "Bharti Airtel Ltd",
"BPCL": "Bharat Petroleum Corporation Ltd",
"BRITANNIA": "Britannia Industries Ltd",
"CIPLA": "Cipla Ltd",
"COALINDIA": "Coal India Ltd",
"DIVISLAB": "Divi's Laboratories Ltd",
"DRREDDY": "Dr. Reddy's Laboratories Ltd",
"EICHERMOT": "Eicher Motors Ltd",
"GRASIM": "Grasim Industries Ltd",
"HCLTECH": "HCL Technologies Ltd",
"HDFCBANK": "HDFC Bank Ltd",
"HDFCLIFE": "HDFC Life Insurance Company Ltd",
"HEROMOTOCO": "Hero MotoCorp Ltd",
"HINDALCO": "Hindalco Industries Ltd",
"HINDUNILVR": "Hindustan Unilever Ltd",
"ICICIBANK": "ICICI Bank Ltd",
"INDUSINDBK": "IndusInd Bank Ltd",
"INFY": "Infosys Ltd",
"ITC": "ITC Ltd",
"JSWSTEEL": "JSW Steel Ltd",
"KOTAKBANK": "Kotak Mahindra Bank Ltd",
"LT": "Larsen & Toubro Ltd",
"M&M": "Mahindra & Mahindra Ltd",
"MARUTI": "Maruti Suzuki India Ltd",
"NESTLEIND": "Nestle India Ltd",
"NTPC": "NTPC Ltd",
"ONGC": "Oil & Natural Gas Corporation Ltd",
"POWERGRID": "Power Grid Corporation of India Ltd",
"RELIANCE": "Reliance Industries Ltd",
"SBILIFE": "SBI Life Insurance Company Ltd",
"SBIN": "State Bank of India",
"SHREECEM": "Shree Cement Ltd",
"SUNPHARMA": "Sun Pharmaceutical Industries Ltd",
"TATACONSUM": "Tata Consumer Products Ltd",
"TATAMOTORS": "Tata Motors Ltd",
"TATASTEEL": "Tata Steel Ltd",
"TCS": "Tata Consultancy Services Ltd",
"TECHM": "Tech Mahindra Ltd",
"TITAN": "Titan Company Ltd",
"ULTRACEMCO": "UltraTech Cement Ltd",
"UPL": "UPL Ltd",
"WIPRO": "Wipro Ltd"
}


advice_queries = ['1. I bought Nvidia (NVDA) at $960 but it’s now near $1,200. Should I trim my position or continue riding the AI wave?\n',
'2. With Amazon (AMZN) up after its Prime Day preview, is it smart to buy now or wait for a post‑event dip?\n',
'3. Tesla (TSLA) just announced another price cut in Europe. Does that make the stock a buy, sell, or hold for the next 12\u202fmonths?\n',
'4. After the recent pullback in Advanced Micro Devices (AMD), is this an attractive entry point or a value trap?\n',
'5. Is Meta Platforms (META) still a good buy given its metaverse spending, or should I rotate into Alphabet (GOOGL)?\n',
'6. With Apple (AAPL) launching new Vision Pro features, should I increase my allocation or wait for earnings clarity?\n',
'7. Should I add to my position in Intuit (INTU) before the next tax season, or is most of the growth priced in?\n',
'8. Broadcom (AVGO) just completed its VMware integration. Buy on synergy optimism or lock in profits?\n',
'9. Is PayPal (PYPL) a turnaround play worth buying, or should I consider Block (SQ) instead?\n',
'10. Netflix (NFLX) introduced ad‑supported tiers; does that warrant a fresh buy, or should I stick with Paramount Streaming (PARA)?\n',
'11. With the semiconductor shortage easing, do Intel (INTC) prospects justify a buy over Qualcomm (QCOM)?\n',
'12. Should I lighten my stake in Adobe (ADBE) after its Figma integration delays?\n',
'13. Is it too late to buy Advanced Energy Solutions ETF (QQQJ), or does it still have upside for 2026?\n',
'14. Zoom Video (ZM) is pivoting to enterprise AI. Buy now or avoid?\n',
'15. Given Costco’s (COST) steady membership model, should I accumulate shares despite its high valuation?\n',
'16. Considering Marvell Technology (MRVL)’s data‑center momentum, is it a better buy than Micron (MU)?\n',
'17. I hold DoorDash (DASH) at a loss. Should I double down, hold, or exit?\n',
'18. Is Datadog (DDOG) attractive after its post‑earnings dip, or is Snowflake (SNOW) the stronger play?\n',
'19. With rising defense budgets, should I buy Palantir (PLTR) now?\n',
'20. Roku (ROKU) rallied on advertising gains. Is it prudent to sell into strength?\n',
'21. Does eBay (EBAY) still offer value, or should I reallocate to Etsy (ETSY)?\n',
'22. After strong earnings, is Chipotle’s (CMG) Nasdaq‑listed stock overextended or worth holding long term?\n',
'23. Should I initiate a position in Lucid Motors (LCID) or wait for clearer EV demand data?\n',
'24. Is Cloudflare (NET) a buy on cybersecurity tailwinds, or should I consider CrowdStrike (CRWD) instead?\n',
'25. Given KLA Corporation (KLAC)’s robust backlog, is now the time to add shares or lock in gains?\n',
'26. I hold Alphabet (GOOGL) and Meta Platforms (META), both up ~20% this year. Should I sell one and reinvest in Amazon (AMZN) or continue holding all three?\n',
'27. With Tesla (TSLA) and Rivian (RIVN) under pressure, should I swap into Lucid (LCID) or exit the EV sector entirely?\n',
'28. Nvidia (NVDA) and AMD (AMD) are leading in AI chips. Is it wise to hold both, or consolidate into one for better compounding?\n',
'29. Between PayPal (PYPL), Block (SQ), and SoFi (SOFI), which fintech stock offers the best recovery potential over the next 3 years?\n',
'30. I’m invested in Netflix (NFLX) and Roku (ROKU). Should I rotate into Paramount (PARA) or stay in current streaming plays?\n',
'31. Apple (AAPL) and Broadcom (AVGO) are core to my portfolio. Should I add Qualcomm (QCOM) for more semi exposure or avoid overconcentration?\n',
'32. I’m overweight on CrowdStrike (CRWD) and Palo Alto Networks (PANW). Should I diversify with Zscaler (ZS) or reduce my cybersecurity sector exposure?\n',
'33. Holding Microsoft (MSFT) and Adobe (ADBE) for 2 years. Should I take partial profits and enter Snowflake (SNOW) or MongoDB (MDB)?\n',
'34. My portfolio includes Marvell (MRVL), Intel (INTC), and Taiwan Semi ADR (TSM). Should I exit any of these in favor of KLA Corp (KLAC)?\n',
'35. I missed the rally in Tesla (TSLA) and Nvidia (NVDA). Is now still a good time to enter, or should I consider Alphabet (GOOGL) instead?\n',
'36. Amazon (AMZN), eBay (EBAY), and Etsy (ETSY) make up 30% of my portfolio. Is this too much e-commerce exposure? Should I diversify?\n',
'37. Should I hold both Zoom (ZM) and DocuSign (DOCU) post-pandemic, or exit in favor of more AI-driven firms like Palantir (PLTR)?\n',
'38. Between Datadog (DDOG), New Relic (NEWR), and ServiceNow (NOW), which observability/cloud ops stock should I double down on?\n',
'39. Netflix (NFLX), Disney (DIS), and Warner Bros Discovery (WBD)—which has the best upside in the streaming war for 2025?\n',
'40. I’m invested in Robinhood (HOOD), Coinbase (COIN), and SoFi (SOFI). Are any worth holding long-term, or is it time to cut losses?\n',
'41. Should I add Amazon (AMZN) and Meta (META) to my current holdings of Google (GOOGL) and Apple (AAPL) for more FAANG exposure?\n',
'42. Between Micron (MU), Lam Research (LRCX), and Applied Materials (AMAT), which chip stock offers the best risk-adjusted growth?\n',
'43. I hold Spotify (SPOT) and SiriusXM (SIRI). Should I add Apple (AAPL) or move away from the audio space altogether?\n',
'44. Tesla (TSLA) and Lucid (LCID) are in my portfolio. Should I add Nio (NIO) or shift to battery-tech players like Enphase (ENPH)?\n',
'45. With Intuit (INTU) and Salesforce (CRM) doing well, should I add HubSpot (HUBS) or keep portfolio concentration tight?\n',
'46. Holding Apple (AAPL), Microsoft (MSFT), and Nvidia (NVDA)—should I diversify into lesser-known growth stocks or stay top-heavy?\n',
'47. Between Pinterest (PINS), Snap (SNAP), and Meta (META), which social media stock is best for 2–4 year growth?\n',
'48. Airbnb (ABNB), Uber (UBER), and Lyft (LYFT) are down from peaks. Which has the best recovery potential by 2026?\n',
'49. I’m overweight QQQ and also own TQQQ. Is this redundant or a viable leveraged play? Should I reduce one?\n',
'50. Should I trim Palantir (PLTR) and Snowflake (SNOW) to reduce volatility or double down now that AI adoption is surging?\n',
"51. I’m considering splitting capital between ASML, Intuit (INTU), and Marvell (MRVL). What’s a smart way to allocate across these three for the next 12 months?",
"52. I already hold Cadence Design (CDNS) and Lam Research (LRCX). Should I add more now or wait for a better entry?",
"53. I just started investing and bought DocuSign (DOCU), Biogen (BIIB), and Enphase (ENPH). Should I consolidate or keep all three?",
"54. How should I divide fresh investment across Microchip Technology (MCHP), Seagen (SGEN), and Comcast (CMCSA)?",
"55. I have significant exposure to ASML, Lam Research, and KLA (KLAC). Is this too much semiconductor exposure?",
"56. Between Intuit, Monster Beverage (MNST), and eBay (EBAY), where would you focus fresh capital this quarter?",
"57. I’m overweight Fastenal (FAST) but underweight NetEase (NTES). Should I rebalance or stay the course?",
"58. With new money to invest, how should I allocate among PDD, Marvell, and Cadence?",
"59. I hold DocuSign and CoStar Group (CSGP). Should I diversify into something outside of SaaS?",
"60. Is it risky to have both Seagen and Biogen in a concentrated biotech position? Or are they complementary?",
"61. I just bought CDNS, ENPH, and IDEXX Laboratories (IDXX). Should I add more capital now or wait for a dip?",
"62. Between Comcast, Monster, and Ross Stores (ROST), which offers the best defensive positioning right now?",
"63. My core holdings are ASML, INTU, and BIIB. Is that well-balanced or overly growth-focused?",
"64. I’m starting fresh — should I build around KLA (KLAC), CoStar Group, and eBay, or swap one for a fintech like Intuit?",
"65. I own Enphase and PDD. Should I hedge with something more stable like ADP or ROST?",
"66. How would you allocate ₹1L across IDXX, MRVL, and CSGP for the next 12 months?",
"67. Is it better to average up in Lam Research and ASML, or look at overlooked names like MCHP or SGEN?",
"68. With just ₹50K to invest, would you go all-in on INTU, or split it between EBAY and FAST?",
"69. I already own CDNS, KLAC, and MCHP. Is this too much exposure to the semiconductor supply chain?",
"70. Holding DOCU, ENPH, and MNST. Would you consider trimming one to add biotech or e-commerce exposure?",
"71. For a 3-year horizon, how would you split new investment between INTU, IDXX, and NTES?",
"72. I’m overweight PDD and ENPH, underweight CDNS and FAST. Rebalance or keep riding the winners?",
"73. Should I sell part of my BIIB position to fund new exposure in CSGP or ADP?",
"74. I want to rotate some capital out of eBay and into either LRCX or SGEN. Which has better long-term upside?",
"75. I’ve got equal exposure to INTU, ROST, NTES, and MCHP. Is this too diversified, or just right for a growth + stability portfolio?",
"76. Is it a good time to re-enter ASML, or is it better to wait for a correction and invest in something like DOCU or BIIB?",
"77. I’ve built a portfolio around ENPH, IDXX, and MRVL. Am I missing out by not having exposure to traditional retail like ROST?",
"78. Should I add more to Comcast and eBay, or is it time to look into something more tech-heavy like Cadence or Fastenal?",
"79. After trimming INTU and KLAC, I want to rotate into either SGEN or CDNS. Which has better upside over 5 years?",
"80. I’ve held Biogen and Seagen for a while. Should I diversify into clean tech like Enphase or energy storage?",
"81. Would you recommend building a long-term core using ADP, ASML, and CSGP, or is that too concentrated?",
"82. Thinking about entering Monster Beverage, NetEase, and Lam Research—how should I spread risk among them?",
"83. I’ve held onto MCHP and MRVL since last year. Is it time to rotate into something more stable like ADP or CMCSA?",
"84. Should I replace my position in DOCU with IDXX or just hold through volatility?",
"85. I’m very heavy in eBay and Monster Beverage. Is it time to rotate into growth like PDD or Cadence Design?",
"86. What are the risks of holding both NTES and BIIB in a concentrated portfolio?",
"87. Can I treat ASML, INTU, and ENPH as a solid long-term trio for my 10-year plan?",
"88. I hold MCHP, CSGP, and DOCU. Is this portfolio too exposed to tech or is it reasonably balanced?",
"89. If I have to pick two: Cadence vs KLAC or INTU vs IDXX — which combo has the stronger long-term runway?",
"90. Thinking of reallocating from Monster and eBay into either biotech or clean energy. What’s the best path?",
"91. I’ve had solid gains from ADP and ROST. Should I let them run or take profits and rotate into MRVL or NTES?",
"92. Are CMCSA, DOCU, and IDXX a smart trio to build a low-volatility but still growing portfolio?",
"93. Would you allocate a fresh ₹2L lump sum into ENPH, SGEN, and CSGP right now?",
"94. Should I keep small positions in LRCX, BIIB, and MNST or consolidate into one high-conviction pick?",
"95. What’s the ideal weight for a 4-stock mix of ASML, KLAC, INTU, and ROST?",
"96. Is a portfolio of FAST, CDNS, and SGEN diversified enough or am I missing out on core tech?",
"97. With rising interest in biotech, should I go heavier into Seagen or split between Biogen and ENPH?",
"98. I’m deciding between scaling my INTU position or starting a new one in CoStar or MRVL. Thoughts?",
"99. I’ve held eBay for a while, but I’m considering rotating into either clean energy or industrials. What’s better for 2025?",
"100. I'm looking at ADP, NTES, and KLAC for long-term growth. Which two have better upside if I can only pick a pair?"
]
